import type { FastifyPluginAsync } from "fastify";
import { JourneyNavigator, JourneyStep } from "./navigator.js";

interface SearchBody {
  Body: { searchId: string };
}

const searchRoute: FastifyPluginAsync = async (fastify) => {
  fastify.get("/:journeyId/search", async (request, reply) => {
    const params = request.params as { journeyId: string };

    // We pass the POST action URL generated by the navigator to the template
    const formActionUrl = JourneyNavigator.getPath(
      JourneyStep.SEARCH,
      params.journeyId,
    );

    return reply.view("search.njk", {
      journeyId: params.journeyId,
      formAction: formActionUrl,
    });
  });

  fastify.post<SearchBody>("/:journeyId/search", async (request, reply) => {
    const params = request.params as { journeyId: string };
    const { searchId } = request.body;

    // 1. Mutate State
    request.setJourneyData({ searchId });

    // 2. Compute Context
    const isValidEntity = searchId === "123" || searchId === "456";

    // 3. Delegate to Navigator
    const nextPath = JourneyNavigator.getNextPath(
      JourneyStep.SEARCH,
      { isValidEntity },
      params.journeyId,
    );

    return reply.redirect(nextPath);
  });
};

export default searchRoute;
